"""Change delete cascade to set null

Revision ID: 447959c817db
Revises: cdb756595d35
Create Date: 2023-07-28 02:32:55.378524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447959c817db'
down_revision = 'cdb756595d35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_topics_responsible_id_users', 'topics', type_='foreignkey')
    op.create_foreign_key(op.f('fk_topics_responsible_id_users'), 'topics', 'users', ['responsible_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_topics_responsible_id_users'), 'topics', type_='foreignkey')
    op.create_foreign_key('fk_topics_responsible_id_users', 'topics', 'users', ['responsible_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
