"""Added tables for random coffee

Revision ID: 4b8227d2da51
Revises: 447959c817db
Create Date: 2023-11-22 10:53:50.418304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8227d2da51'
down_revision = '447959c817db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_coffee',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_random_coffee_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_random_coffee'))
    )
    op.create_table('random_coffee_pairs',
    sa.Column('random_coffee_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('first_id', sa.BigInteger(), nullable=False),
    sa.Column('second_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['first_id'], ['users.id'], name=op.f('fk_random_coffee_pairs_first_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_random_coffee_pairs_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['random_coffee_id'], ['random_coffee.id'], name=op.f('fk_random_coffee_pairs_random_coffee_id_random_coffee'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_id'], ['users.id'], name=op.f('fk_random_coffee_pairs_second_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_random_coffee_pairs')),
    sa.UniqueConstraint('group_id', 'first_id', 'second_id', name=op.f('uq_random_coffee_pairs_group_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('random_coffee_pairs')
    op.drop_table('random_coffee')
    # ### end Alembic commands ###
