"""Added message model

Revision ID: 61466764c5c8
Revises: ea409d73e36e
Create Date: 2023-06-28 16:03:06.763226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61466764c5c8'
down_revision = 'ea409d73e36e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('forward_from_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('forward_from_message_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
