"""Added message type

Revision ID: a9b9240e025e
Revises: aaed8b41c0b9
Create Date: 2023-07-20 13:11:05.044592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b9240e025e'
down_revision = 'aaed8b41c0b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    messagetypes = sa.Enum('TASK', 'MESSAGE', name='messagetypes')
    messagetypes.create(op.get_bind(), checkfirst=True)

    op.add_column('messages', sa.Column('type', messagetypes, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')

    messagetypes = sa.Enum('TASK', 'MESSAGE', name='messagetypes')
    messagetypes.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
