"""Rename text to html_text

Revision ID: aaed8b41c0b9
Revises: 1d6ae52b4aeb
Create Date: 2023-07-19 12:57:23.260433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaed8b41c0b9'
down_revision = '1d6ae52b4aeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text', new_column_name='html_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'html_text', new_column_name='text')
    # ### end Alembic commands ###
