"""Added status

Revision ID: d62d1504838a
Revises: db76cf2180bf
Create Date: 2023-07-22 19:09:54.458860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62d1504838a'
down_revision = 'db76cf2180bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status = sa.Enum('COMPLETED', 'PROCESSING', 'NOT_STARTED', 'DECLINED', name='status')
    status.create(op.get_bind(), checkfirst=True)

    op.add_column('messages', sa.Column('status', status, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')

    status = sa.Enum('COMPLETED', 'PROCESSING', 'NOT_STARTED', 'DECLINED', name='status')
    status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
