"""Added message thread id

Revision ID: fcf386700c7c
Revises: 39270bcf2897
Create Date: 2023-07-25 15:14:23.793732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf386700c7c'
down_revision = '39270bcf2897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_thread_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_thread_id')
    # ### end Alembic commands ###
